window.ScoutHubData = {
  players: [
    {
      id: 101,
      firstName: "Kacper",
      lastName: "Nowak",
      email: "kacper.nowak@scouthub.test",
      country: "Polska",
      birthYear: 2010,
      academy: "Akademia Szczecin",
      position: "Lewy obrońca",
      foot: "Lewa",
      heightCm: 169,
      stats: {
        matches: 14,
        minutes: 980,
        goals: 1,
        assists: 4,
        shots: 8,
        shotsOnTarget: 3,
        passes: 520,
        passAcc: 86,
        keyPasses: 15,
        crosses: 28,
        tackles: 34,
        interceptions: 22,
        clearances: 41,
        duels: 160,
        duelsWon: 56,
        cardsY: 2,
        cardsR: 0,
        rating: 7.2
      }
    },
    {
      id: 107,
      firstName: "Mykhailo",
      lastName: "Shevchenko",
      email: "mykhailo.shevchenko@scouthub.test",
      country: "Ukraina",
      birthYear: 2010,
      academy: "Akademia Lwów",
      position: "Środkowy obrońca",
      foot: "Prawa",
      heightCm: 184,
      stats: {
        matches: 15,
        minutes: 1210,
        goals: 2,
        assists: 0,
        shots: 6,
        shotsOnTarget: 3,
        passes: 610,
        passAcc: 88,
        keyPasses: 4,
        crosses: 2,
        tackles: 29,
        interceptions: 27,
        clearances: 58,
        duels: 210,
        duelsWon: 63,
        cardsY: 3,
        cardsR: 0,
        rating: 7.3
      }
    },

    {
      id: 102,
      firstName: "Oleh",
      lastName: "Koval",
      email: "oleh.koval@scouthub.test",
      country: "Ukraina",
      birthYear: 2009,
      academy: "FC Youth Lviv",
      position: "Środkowy pomocnik",
      foot: "Prawa",
      heightCm: 173,
      stats: {
        matches: 18,
        minutes: 1350,
        goals: 5,
        assists: 6,
        shots: 24,
        shotsOnTarget: 10,
        passes: 940,
        passAcc: 84,
        keyPasses: 32,
        crosses: 14,
        tackles: 21,
        interceptions: 16,
        clearances: 10,
        duels: 190,
        duelsWon: 52,
        cardsY: 2,
        cardsR: 0,
        rating: 7.6
      }
    },
    {
      id: 108,
      firstName: "Piotr",
      lastName: "Malinowski",
      email: "piotr.malinowski@scouthub.test",
      country: "Polska",
      birthYear: 2009,
      academy: "Akademia Wrocław",
      position: "Ofensywny pomocnik",
      foot: "Prawa",
      heightCm: 175,
      stats: {
        matches: 16,
        minutes: 1180,
        goals: 6,
        assists: 8,
        shots: 38,
        shotsOnTarget: 16,
        passes: 780,
        passAcc: 82,
        keyPasses: 41,
        crosses: 18,
        tackles: 14,
        interceptions: 9,
        clearances: 6,
        duels: 170,
        duelsWon: 49,
        cardsY: 1,
        cardsR: 0,
        rating: 7.7
      }
    },

    {
      id: 106,
      firstName: "Oskar",
      lastName: "Lewandowski",
      email: "oskar.lewandowski@scouthub.test",
      country: "Polska",
      birthYear: 2011,
      academy: "Akademia Gdańsk",
      position: "Prawy skrzydłowy",
      foot: "Prawa",
      heightCm: 168,
      stats: {
        matches: 13,
        minutes: 860,
        goals: 4,
        assists: 5,
        shots: 29,
        shotsOnTarget: 12,
        passes: 410,
        passAcc: 79,
        keyPasses: 22,
        crosses: 26,
        tackles: 9,
        interceptions: 6,
        clearances: 4,
        duels: 150,
        duelsWon: 48,
        cardsY: 1,
        cardsR: 0,
        rating: 7.7
      }
    },
    {
      id: 109,
      firstName: "Danylo",
      lastName: "Bondarenko",
      email: "danylo.bondarenko@scouthub.test",
      country: "Ukraina",
      birthYear: 2009,
      academy: "Akademia Kijów",
      position: "Lewy skrzydłowy",
      foot: "Lewa",
      heightCm: 172,
      stats: {
        matches: 17,
        minutes: 1240,
        goals: 7,
        assists: 6,
        shots: 44,
        shotsOnTarget: 18,
        passes: 520,
        passAcc: 78,
        keyPasses: 27,
        crosses: 30,
        tackles: 10,
        interceptions: 7,
        clearances: 5,
        duels: 190,
        duelsWon: 50,
        cardsY: 2,
        cardsR: 0,
        rating: 7.5
      }
    },

    {
      id: 103,
      firstName: "Maksym",
      lastName: "Zieliński",
      email: "maksym.zielinski@scouthub.test",
      country: "Polska",
      birthYear: 2008,
      academy: "Akademia Poznań",
      position: "Napastnik",
      foot: "Prawa",
      heightCm: 180,
      stats: {
        matches: 16,
        minutes: 1190,
        goals: 10,
        assists: 2,
        shots: 52,
        shotsOnTarget: 24,
        passes: 310,
        passAcc: 72,
        keyPasses: 9,
        crosses: 4,
        tackles: 6,
        interceptions: 3,
        clearances: 2,
        duels: 180,
        duelsWon: 55,
        cardsY: 1,
        cardsR: 0,
        rating: 7.9
      }
    },
    {
      id: 110,
      firstName: "Kamil",
      lastName: "Wójcik",
      email: "kamil.wojcik@scouthub.test",
      country: "Polska",
      birthYear: 2009,
      academy: "Akademia Kraków",
      position: "Napastnik",
      foot: "Lewa",
      heightCm: 178,
      stats: {
        matches: 15,
        minutes: 1030,
        goals: 8,
        assists: 3,
        shots: 45,
        shotsOnTarget: 20,
        passes: 280,
        passAcc: 70,
        keyPasses: 8,
        crosses: 3,
        tackles: 5,
        interceptions: 2,
        clearances: 1,
        duels: 165,
        duelsWon: 53,
        cardsY: 2,
        cardsR: 0,
        rating: 7.6
      }
    },

    {
      id: 104,
      firstName: "Jan",
      lastName: "Kowalski",
      email: "jan.kowalski@scouthub.test",
      country: "Polska",
      birthYear: 2009,
      academy: "Akademia Warszawa",
      position: "Bramkarz",
      foot: "Prawa",
      heightCm: 186,
      stats: {
        matches: 12,
        minutes: 1080,
        goals: 0,
        assists: 0,
        saves: 42,
        cleanSheets: 4,
        conceded: 13,
        passAcc: 79,
        duels: 0,
        duelsWon: 0,
        cardsY: 0,
        cardsR: 0,
        rating: 7.1
      }
    },
    {
      id: 111,
      firstName: "Artem",
      lastName: "Hrytsenko",
      email: "artem.hrytsenko@scouthub.test",
      country: "Ukraina",
      birthYear: 2010,
      academy: "Akademia Charków",
      position: "Bramkarz",
      foot: "Prawa",
      heightCm: 182,
      stats: {
        matches: 14,
        minutes: 1260,
        goals: 0,
        assists: 0,
        saves: 50,
        cleanSheets: 5,
        conceded: 14,
        passAcc: 77,
        duels: 0,
        duelsWon: 0,
        cardsY: 1,
        cardsR: 0,
        rating: 7.4
      }
    }
  ]
};
