<?php
declare(strict_types=1);

$STAT_LABELS_PL = [
  "matches"        => "Mecze",
  "minutes"        => "Minuty",
  "goals"          => "Gole",
  "assists"        => "Asysty",
  "shots"          => "Strzały",
  "shotsOnTarget"  => "Strzały celne",
  "passes"         => "Podania",
  "passAcc"        => "Celność podań (%)",
  "keyPasses"      => "Kluczowe podania",
  "crosses"        => "Dośrodkowania",
  "tackles"        => "Odbiory",
  "interceptions"  => "Przechwyty",
  "clearances"     => "Wybicia",
  "duels"          => "Pojedynki",
  "duelsWon"       => "Wygrane pojedynki (%)",
  "cardsY"         => "Kartki żółte",
  "cardsR"         => "Kartki czerwone",

  // BRAMKARZ
  "saves"          => "Obrony",
  "cleanSheets"    => "Czyste konta",
  "conceded"       => "Stracone bramki",

  "rating"         => "Ocena",
];

$PLAYERS = [
  [
    "id" => 101,
    "firstName" => "Kacper",
    "lastName" => "Nowak",
    "email" => "kacper.nowak@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2010,
    "academy" => "Akademia Szczecin",
    "position" => "Lewy obrońca",
    "foot" => "Lewa",
    "heightCm" => 169,
    "stats" => [
      "Mecze" => 14,
      "Minuty" => 980,
      "Gole" => 1,
      "Asysty" => 4,
      "Strzały" => 8,
      "Strzały celne" => 3,
      "Podania" => 520,
      "Celność podań (%)" => 86,
      "Kluczowe podania" => 15,
      "Dośrodkowania" => 28,
      "Odbiory" => 34,
      "Przechwyty" => 22,
      "Wybicia" => 41,
      "Pojedynki" => 160,
      "Wygrane pojedynki (%)" => 56,
      "Kartki żółte" => 2,
      "Kartki czerwone" => 0,
      "Ocena" => 7.2,
    ],
  ],
  [
    "id" => 107,
    "firstName" => "Mykhailo",
    "lastName" => "Shevchenko",
    "email" => "mykhailo.shevchenko@scouthub.test",
    "country" => "Ukraina",
    "birthYear" => 2010,
    "academy" => "Akademia Lwów",
    "position" => "Środkowy obrońca",
    "foot" => "Prawa",
    "heightCm" => 184,
    "stats" => [
      "Mecze" => 15,
      "Minuty" => 1210,
      "Gole" => 2,
      "Asysty" => 0,
      "Strzały" => 6,
      "Strzały celne" => 3,
      "Podania" => 610,
      "Celność podań (%)" => 88,
      "Kluczowe podania" => 4,
      "Dośrodkowania" => 2,
      "Odbiory" => 29,
      "Przechwyty" => 27,
      "Wybicia" => 58,
      "Pojedynki" => 210,
      "Wygrane pojedynki (%)" => 63,
      "Kartki żółte" => 3,
      "Kartki czerwone" => 0,
      "Ocena" => 7.3,
    ],
  ],

  [
    "id" => 102,
    "firstName" => "Oleh",
    "lastName" => "Koval",
    "email" => "oleh.koval@scouthub.test",
    "country" => "Ukraina",
    "birthYear" => 2009,
    "academy" => "FC Youth Lviv",
    "position" => "Środkowy pomocnik",
    "foot" => "Prawa",
    "heightCm" => 173,
    "stats" => [
      "Mecze" => 18,
      "Minuty" => 1350,
      "Gole" => 5,
      "Asysty" => 6,
      "Strzały" => 24,
      "Strzały celne" => 10,
      "Podania" => 940,
      "Celność podań (%)" => 84,
      "Kluczowe podania" => 32,
      "Dośrodkowania" => 14,
      "Odbiory" => 21,
      "Przechwyty" => 16,
      "Wybicia" => 10,
      "Pojedynki" => 190,
      "Wygrane pojedynki (%)" => 52,
      "Kartki żółte" => 2,
      "Kartki czerwone" => 0,
      "Ocena" => 7.6,
    ],
  ],
  [
    "id" => 108,
    "firstName" => "Piotr",
    "lastName" => "Malinowski",
    "email" => "piotr.malinowski@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2009,
    "academy" => "Akademia Wrocław",
    "position" => "Ofensywny pomocnik",
    "foot" => "Prawa",
    "heightCm" => 175,
    "stats" => [
      "Mecze" => 16,
      "Minuty" => 1180,
      "Gole" => 6,
      "Asysty" => 8,
      "Strzały" => 38,
      "Strzały celne" => 16,
      "Podania" => 780,
      "Celność podań (%)" => 82,
      "Kluczowe podania" => 41,
      "Dośrodkowania" => 18,
      "Odbiory" => 14,
      "Przechwyty" => 9,
      "Wybicia" => 6,
      "Pojedynki" => 170,
      "Wygrane pojedynki (%)" => 49,
      "Kartki żółte" => 1,
      "Kartki czerwone" => 0,
      "Ocena" => 7.7,
    ],
  ],

  [
    "id" => 106,
    "firstName" => "Oskar",
    "lastName" => "Lewandowski",
    "email" => "oskar.lewandowski@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2011,
    "academy" => "Akademia Gdańsk",
    "position" => "Prawy skrzydłowy",
    "foot" => "Prawa",
    "heightCm" => 168,
    "stats" => [
      "Mecze" => 13,
      "Minuty" => 860,
      "Gole" => 4,
      "Asysty" => 5,
      "Strzały" => 29,
      "Strzały celne" => 12,
      "Podania" => 410,
      "Celność podań (%)" => 79,
      "Kluczowe podania" => 22,
      "Dośrodkowania" => 26,
      "Odbiory" => 9,
      "Przechwyty" => 6,
      "Wybicia" => 4,
      "Pojedynki" => 150,
      "Wygrane pojedynki (%)" => 48,
      "Kartki żółte" => 1,
      "Kartki czerwone" => 0,
      "Ocena" => 7.7,
    ],
  ],
  [
    "id" => 109,
    "firstName" => "Danylo",
    "lastName" => "Bondarenko",
    "email" => "danylo.bondarenko@scouthub.test",
    "country" => "Ukraina",
    "birthYear" => 2009,
    "academy" => "Akademia Kijów",
    "position" => "Lewy skrzydłowy",
    "foot" => "Lewa",
    "heightCm" => 172,
    "stats" => [
      "Mecze" => 17,
      "Minuty" => 1240,
      "Gole" => 7,
      "Asysty" => 6,
      "Strzały" => 44,
      "Strzały celne" => 18,
      "Podania" => 520,
      "Celność podań (%)" => 78,
      "Kluczowe podania" => 27,
      "Dośrodkowania" => 30,
      "Odbiory" => 10,
      "Przechwyty" => 7,
      "Wybicia" => 5,
      "Pojedynki" => 190,
      "Wygrane pojedynki (%)" => 50,
      "Kartki żółte" => 2,
      "Kartki czerwone" => 0,
      "Ocena" => 7.5,
    ],
  ],

  [
    "id" => 103,
    "firstName" => "Maksym",
    "lastName" => "Zieliński",
    "email" => "maksym.zielinski@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2008,
    "academy" => "Akademia Poznań",
    "position" => "Napastnik",
    "foot" => "Prawa",
    "heightCm" => 180,
    "stats" => [
      "Mecze" => 16,
      "Minuty" => 1190,
      "Gole" => 10,
      "Asysty" => 2,
      "Strzały" => 52,
      "Strzały celne" => 24,
      "Podania" => 310,
      "Celność podań (%)" => 72,
      "Kluczowe podania" => 9,
      "Dośrodkowania" => 4,
      "Odbiory" => 6,
      "Przechwyty" => 3,
      "Wybicia" => 2,
      "Pojedynki" => 180,
      "Wygrane pojedynki (%)" => 55,
      "Kartki żółte" => 1,
      "Kartki czerwone" => 0,
      "Ocena" => 7.9,
    ],
  ],
  [
    "id" => 110,
    "firstName" => "Kamil",
    "lastName" => "Wójcik",
    "email" => "kamil.wojcik@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2009,
    "academy" => "Akademia Kraków",
    "position" => "Napastnik",
    "foot" => "Lewa",
    "heightCm" => 178,
    "stats" => [
      "Mecze" => 15,
      "Minuty" => 1030,
      "Gole" => 8,
      "Asysty" => 3,
      "Strzały" => 45,
      "Strzały celne" => 20,
      "Podania" => 280,
      "Celność podań (%)" => 70,
      "Kluczowe podania" => 8,
      "Dośrodkowania" => 3,
      "Odbiory" => 5,
      "Przechwyty" => 2,
      "Wybicia" => 1,
      "Pojedynki" => 165,
      "Wygrane pojedynki (%)" => 53,
      "Kartki żółte" => 2,
      "Kartki czerwone" => 0,
      "Ocena" => 7.6,
    ],
  ],

  [
    "id" => 104,
    "firstName" => "Jan",
    "lastName" => "Kowalski",
    "email" => "jan.kowalski@scouthub.test",
    "country" => "Polska",
    "birthYear" => 2009,
    "academy" => "Akademia Warszawa",
    "position" => "Bramkarz",
    "foot" => "Prawa",
    "heightCm" => 186,
    "stats" => [
      "Mecze" => 12,
      "Minuty" => 1080,
      "Gole" => 0,
      "Asysty" => 0,
      "Obrony" => 42,
      "Czyste konta" => 4,
      "Stracone bramki" => 13,
      "Celność podań (%)" => 79,
      "Pojedynki" => 0,
      "Wygrane pojedynki (%)" => 0,
      "Kartki żółte" => 0,
      "Kartki czerwone" => 0,
      "Ocena" => 7.1,
    ],
  ],
  [
    "id" => 111,
    "firstName" => "Artem",
    "lastName" => "Hrytsenko",
    "email" => "artem.hrytsenko@scouthub.test",
    "country" => "Ukraina",
    "birthYear" => 2010,
    "academy" => "Akademia Charków",
    "position" => "Bramkarz",
    "foot" => "Prawa",
    "heightCm" => 182,
    "stats" => [
      "Mecze" => 14,
      "Minuty" => 1260,
      "Gole" => 0,
      "Asysty" => 0,
      "Obrony" => 50,
      "Czyste konta" => 5,
      "Stracone bramki" => 14,
      "Celność podań (%)" => 77,
      "Pojedynki" => 0,
      "Wygrane pojedynki (%)" => 0,
      "Kartki żółte" => 1,
      "Kartki czerwone" => 0,
      "Ocena" => 7.4,
    ],
  ],
];